site_name: Fautil Documentation
theme:
  name: material

# 添加插件
plugins:
  - search

# 配置文档目录
docs_dir: docs
site_dir: site

# 配置导航
nav:
  - 首页: index.md
  - 快速开始: quickstart.md
  - 用户指南: user-guide.md
  - API 参考: api.md
  - 示例: examples.md
